import { ChainIds } from '@ensofinance/shortcuts-builder/types';
import { BigNumberish } from '@ethersproject/bignumber';
import { StaticJsonRpcProvider } from '@ethersproject/providers';

import { Beets_Sts_Deposit_Shortcut } from '../shortcuts/beets/sts_deposit';
import { Beets_Sts_Redeem_Shortcut } from '../shortcuts/beets/sts_redeem';
import { Origin_Wos_Deposit_Shortcut } from '../shortcuts/origin/wos_deposit';
import { Origin_Wos_Redeem_Shortcut } from '../shortcuts/origin/wos_redeem';
import { Rings_Wstkscusd_Deposit_Shortcut } from '../shortcuts/rings/wstkscusd_deposit';
import { Rings_Wstkscusd_Redeem_Shortcut } from '../shortcuts/rings/wstkscusd_redeem';
import { Silo_Ws_Deposit_Shortcut } from '../shortcuts/silo/ws_deposit';
import { Silo_Ws_Redeem_Shortcut } from '../shortcuts/silo/ws_redeem';
import { StableJack_PtSts_Deposit_Shortcut } from '../shortcuts/stablejack/PT-stS_deposit';
import { StableJack_PtSts_Redeem_Shortcut } from '../shortcuts/stablejack/PT-stS_redeem';
import { StableJack_PtWos_Deposit_Shortcut } from '../shortcuts/stablejack/PT-wOS_deposit';
import { StableJack_PtWos_Redeem_Shortcut } from '../shortcuts/stablejack/PT-wOS_redeem';
import { StableJack_YtSts_Deposit_Shortcut } from '../shortcuts/stablejack/YT-stS_deposit';
import { StableJack_YtSts_Redeem_Shortcut } from '../shortcuts/stablejack/YT-stS_redeem';
import { StableJack_YtWos_Deposit_Shortcut } from '../shortcuts/stablejack/YT-wOS_deposit';
import { StableJack_YtWos_Redeem_Shortcut } from '../shortcuts/stablejack/YT-wOS_redeem';
import { BuiltShortcut, Shortcut } from '../types';
import { buildVerificationHash } from './utils';

// TODO: this structure can be generated by iterating `supportedShortcuts`, building each shortcut,
// and mapping them to the `shortcuts` object (using name from `<Shortcut>.name`).
export const shortcuts: Record<string, Record<string, Shortcut>> = {
  beets: {
    'sts-deposit': new Beets_Sts_Deposit_Shortcut(),
    'sts-redeem': new Beets_Sts_Redeem_Shortcut(),
  },
  origin: {
    'wos-deposit': new Origin_Wos_Deposit_Shortcut(),
    'wos-redeem': new Origin_Wos_Redeem_Shortcut(),
  },
  silo: {
    'ws-deposit': new Silo_Ws_Deposit_Shortcut(),
    'ws-redeem': new Silo_Ws_Redeem_Shortcut(),
  },
  stablejack: {
    'pt-sts-deposit': new StableJack_PtSts_Deposit_Shortcut(),
    'pt-sts-redeem': new StableJack_PtSts_Redeem_Shortcut(),
    'pt-wos-deposit': new StableJack_PtWos_Deposit_Shortcut(),
    'pt-wos-redeem': new StableJack_PtWos_Redeem_Shortcut(),
    'yt-sts-deposit': new StableJack_YtSts_Deposit_Shortcut(),
    'yt-sts-redeem': new StableJack_YtSts_Redeem_Shortcut(),
    'yt-wos-deposit': new StableJack_YtWos_Deposit_Shortcut(),
    'yt-wos-redeem': new StableJack_YtWos_Redeem_Shortcut(),
  },
  rings: {
    wstkscusd_deposit: new Rings_Wstkscusd_Deposit_Shortcut(),
    wstkscusd_redeem: new Rings_Wstkscusd_Redeem_Shortcut(),
  },
};

export function getAllMarkets(): string[] {
  return Object.entries(shortcuts).flatMap(([protocol, markets]) =>
    Object.keys(markets).map((market) => `${protocol}-${market}`),
  );
}

export const supportedShortcuts = [
  Silo_Ws_Deposit_Shortcut,
  Silo_Ws_Redeem_Shortcut,
  StableJack_PtSts_Deposit_Shortcut,
  StableJack_PtSts_Redeem_Shortcut,
  StableJack_PtWos_Deposit_Shortcut,
  StableJack_PtWos_Redeem_Shortcut,
  StableJack_YtSts_Deposit_Shortcut,
  StableJack_YtSts_Redeem_Shortcut,
  StableJack_YtWos_Deposit_Shortcut,
  StableJack_YtWos_Redeem_Shortcut,
  Origin_Wos_Deposit_Shortcut,
  Origin_Wos_Redeem_Shortcut,
  Rings_Wstkscusd_Deposit_Shortcut,
  Rings_Wstkscusd_Redeem_Shortcut,
  Beets_Sts_Deposit_Shortcut,
  Beets_Sts_Redeem_Shortcut,
];

export async function buildShortcutsHashMap(
  chainId: number,
  provider: StaticJsonRpcProvider,
): Promise<Record<string, Shortcut>> {
  const shortcutsArray = [];
  for (const protocol in shortcuts) {
    for (const market in shortcuts[protocol]) {
      const shortcut = shortcuts[protocol][market];
      if (shortcut.inputs[chainId]) shortcutsArray.push(shortcuts[protocol][market]);
    }
  }
  const hashArray = await Promise.all(
    shortcutsArray.map(async (shortcut) => {
      const { script, metadata } = await shortcut.build(chainId, provider);
      return buildVerificationHash(metadata.tokensOut![0], script);
    }),
  );
  const shortcutsHashMap: Record<string, Shortcut> = {};
  for (const i in shortcutsArray) {
    shortcutsHashMap[hashArray[i]] = shortcutsArray[i];
  }
  return shortcutsHashMap;
}

export async function buildShortcut(
  chainId: ChainIds,
  provider: StaticJsonRpcProvider,
  shortcut: Shortcut,
  amountsIn: BigNumberish[],
): Promise<BuiltShortcut> {
  let builtShortcut: BuiltShortcut;
  try {
    builtShortcut = await shortcut.build(chainId, provider);
  } catch (error) {
    throw new Error(`Unexpected error building shortcut: ${shortcut.name}. Reason: ${error}`);
  }

  const { script, metadata } = builtShortcut;

  // Validate metadata
  const { tokensIn, tokensOut } = metadata;
  if (!tokensIn) {
    throw new Error(
      `Invalid 'metadata.tokensIn' in shortcut: ${shortcut.name}. "tokensIn" array must have one item at least`,
    );
  }
  if (!tokensOut) {
    throw new Error(
      `Invalid 'metadata.tokensIn' in shortcut: ${shortcut.name}. "tokensOut" array must have one item at least`,
    );
  }
  if (amountsIn.length != tokensIn.length) {
    throw new Error(
      `Invalid 'metadata.amountsIn' and 'metadata.tokensIn' in shortcut: ${shortcut.name}. Length mismatch`,
    );
  }

  return { script, metadata };
}
