name: CI

on:
  push:
    branches:
      - '*' # Trigger on any push to any branch

  pull_request:
    branches:
      - main # Trigger on any PR to the main branch
    types:
      - opened
      - synchronize
      - reopened # Trigger only on non-draft PRs (draft PRs are not included)

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Set up Node.js environment using .nvmrc
      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      # Set up npm authentication with secret
      - name: Set up npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      # Set up environment variables
      - name: Set up environment variables
        run: echo "RPC_URL_SONIC=${{ secrets.RPC_URL_SONIC}}" >> $GITHUB_ENV

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install node & foundry dependencies
      - name: Install dependencies
        run: pnpm registryup

      # Lint files (similar to Husky)
      - name: Run lint checks
        run: pnpm lint:check

      # Run tests
      - name: Run tests
        run: pnpm test:simulations
